name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/checkout@master
    - uses: codecov/codecov-action@v1
      with:
<<<<<<< HEAD
        file: ./coverage.opencover.xml # optional
=======
        token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
        file: ./LingoWordsTest/coverage.opencover.xml # optional
>>>>>>> 17bf933fa5e6f16ae88e3204915609f88c5483ca
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
<<<<<<< HEAD
      run: dotnet test --no-restore --verbosity normal
=======
      run: dotnet test --no-restore --verbosity normal

 
>>>>>>> 17bf933fa5e6f16ae88e3204915609f88c5483ca
